spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring-social-login?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: spring-social
        password: test1234

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

